#!/bin/sh

# =========
# Autostart
# =========
# Start key bindings
sxhkd &

#Start wmname fix for java windows
wmname LG3D &

# Start compositor
picom --experimental-backends  &

# Start polkit agent
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start mouse
xsetroot -cursor_name left_ptr &

# Start status bar
bash /home/nic/.config/polybar/launch.sh &

# Start Spotify Fix Script
#bash /home/nic/.config/bspwm/spotify-script.sh &

# ==========
# Workspaces
# ==========
bspc monitor DP-2 -d one two three 
bspc monitor HDMI-0 -d four five six

# =====
# Tiled
# =====
# Border width
bspc config border_width 0

# Gap between windows
bspc config window_gap  20
bspc config top_padding 25



# Windows split ratio
bspc config split_ratio 0.5

# Rounded Corners?
bspc config border_radius 0

#Mouse move focus 
bspc config focus_follows_pointer true	

# =======
# Monocle
# =======
# Borders
bspc config borderless_monocle false

# Gap
bspc config gapless_monocle false

# ============
# Window Rules
# ============
bspc rule -a firefox       desktop=^2
bspc rule -a Spotify	   desktop=^4 state=pseudo_tiled
bspc rule -a spotify 	   desktop=^4 state=pseudo_tiled
bspc rule -a Gwe 		   desktop=^4
bspc rule -a Steam 		   desktop =^4 
bspc rule -a steam 		   desktop =^4
bspc rule -a Code 	   	   desktop =^3
bspc rule -a jetbrains-clion desktop=^3
bspc rule -a discord	   desktop=^4 state=pseudo_tiled

bspc rule -a URxvt:urxvt_keys_help state=floating
bspc rule -a "origin.exe"  state=floating
bspc rule -a "Wine"		   state=floating

# PyWal Colors 
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"